name: expenses

services:
  expenses:
    image: expenses:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "55007:80"
    env_file:
      - .env
    restart: unless-stopped
