name: expenses

services:
  backend:
    image: expenses-backend:latest
    pull_policy: build
    container_name: expenses-api
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "18110:8000"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    image: expenses-frontend:latest
    pull_policy: build
    container_name: expenses-dashboard
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "55007:3000"
    environment:
      - BACKEND_URL=http://backend:18110
    depends_on:
      - backend
    restart: unless-stopped
